---
- hosts: all
  name: install nginx service and configuration
  vars:
    PORT: 8080

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: present

  - name: nginx config file template
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
    notify: restart nginx service

  - name: enable nginx service
    service:
      name: nginx
      state: started
      enabled: true

  handlers:
  - name: restart nginx service
    service:
      name: nginx
      state: restarted
